-- config = function()
--     retuire("neorg").setup {
--         load = {
--             ["core.defaults"] = {}, -- loads default behavior
--             ["core.concealer"] = {}, -- addds prety icons to docs
--             ["core.dirman"] = { -- manages neorg workspaces
--                 config = {
--                     workspaces = {
--                         notes = "~/notes"
--                     },
--                 },
--             },
--         }
--     }
-- end,
-- run = ":Neorg sync-parsers",
-- requires = "nvim-lua/plenary.nvim",
